DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER
(
    LOGIN_ID       	VARCHAR(15)     NOT NULL,
    PASSWORD    	VARCHAR(100)    NOT NULL,
    NICK_NAME		VARCHAR(30)		NOT NULL,
    CREATED_AT		VARCHAR(30)		NOT NULL,
    CREATED_BY		VARCHAR(30)		NOT NULL,
    UPDATED_AT		VARCHAR(30)		NOT NULL,
    UPDATED_BY		VARCHAR(30)		NOT NULL,
    PRIMARY KEY (LOGIN_ID)
);